### ISSUE TITLE
Having an issue with elm 0.19

### ISSUE THREAD

**Issue by JQuezada0** [ento/elm-doc#38]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/usr/local/lib/python3.7/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/usr/local/lib/python3.7/site-packages/doit/cmd_base.py", line 389, in execute
    self, params, args)
  File "/usr/local/lib/python3.7/site-packages/doit/cmd_base.py", line 270, in load_tasks
    return self._load_from(cmd, self.mod_dict, self.cmd_names)
  File "/usr/local/lib/python3.7/site-packages/doit/cmd_base.py", line 254, in _load_from
    task_list = loader.load_tasks(members, cmd_list, cmd.execute_tasks)
  File "/usr/local/lib/python3.7/site-packages/doit/loader.py", line 147, in load_tasks
    _process_gen()
  File "/usr/local/lib/python3.7/site-packages/doit/loader.py", line 138, in _process_gen
    task_list.extend(generate_tasks(name, ref(), ref.__doc__))
  File "/usr/local/lib/python3.7/site-packages/doit/loader.py", line 313, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/usr/local/lib/python3.7/site-packages/doit/loader.py", line 26, in flat_generator
    for item in gen:
  File "/usr/local/lib/python3.7/site-packages/elm_doc/tasks.py", line 22, in create_tasks
    project_package = elm_package.from_path(project_path)
  File "/usr/local/lib/python3.7/site-packages/elm_doc/elm_package.py", line 31, in from_path
    description = load_description(path / DESCRIPTION_FILENAME)
  File "/usr/local/lib/python3.7/site-packages/elm_doc/elm_package.py", line 50, in load_description
    with open(str(path)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../elm-package.json'
Error:
```

It seems it can't find `elm-package.json`, but the file it should be looking for is `elm.json`. Is there a flag I should be passing?

**Comment by ento** [comment]
There's a prerelease version 1.0.0b3 that supports Elm 0.19 (and drops support for 0.18). Can you install it and try again? I'll update the readme to clarify

**Comment by ento** [comment]
With [1.0.0](https://pypi.org/project/elm-doc/1.0.0/) out, closing issues that pertain to older versions
