### ISSUE TITLE
I have an execution error

### ISSUE THREAD

**Issue by groteck** [ento/elm-doc#6]
When I run the command , it throw this error:
```bash
sudo elm-doc . --output docs --elm-make node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make
.  build_package_docs_json:user/project/1.0.0
########################################
TaskError - taskid:build_package_docs_json:user/project/1.0.0
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elm_doc/decorators.py", line 11, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elm_doc/package_tasks.py", line 80, in build_package_docs_json
    os.environ)
  File "/usr/local/lib/python3.5/dist-packages/elm_doc/__init__.py", line 10, in elm_package_overlayer_env
    overlayer_path = _elm_package_overlayer_path()
  File "/usr/local/lib/python3.5/dist-packages/elm_doc/__init__.py", line 27, in _elm_package_overlayer_path
    "overlay_elm_package", search_paths)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'overlay_elm_package' 
```

**Comment by ento** [comment]
When you installed the package, did you see any errors? If your memory is vague.. (sorry it took a while to respond) could you try reinstalling and see if you can catch anything?

Also, which operating system and version is this?

**Comment by dseebacher** [comment]
Same problem here:

I use Fedora 27 and installed elm-doc with the `--user` flag. 
I had no problem installing it, but I have no clue about the python env, so it might be my fault...

**Comment by ento** [comment]
The latest version [1.0.0](https://pypi.org/project/elm-doc/1.0.0/) no longer uses the overlay module (although it doesn't support Elm 0.18.0); closing issues that pertain to older versions
